### ISSUE TITLE
Not working with PHP 8.1 On-Wards

### ISSUE THREAD

**Issue by mrix2000** [axew3/phpBB-image-attachments-rotation#8]
I have been using this EXT for a few years with all versions of php which have worked fine but now I am stuck on using php8.0 as all post versions php8.1, php8.2 and php8.3 no longer work.
What basically happens when I change from php8.0 to any php version higher the rotation of the image no longer saves after being  rotated.
I am using the latest Google Chrome with Windows 11 on a Dell laptop.

**Comment by axew3** [comment]
Hello. You get no errors but the image is not saved or what?
As said elsewhere, and also by others tested, it is working fine in any php 7.4> and personally i tested it into several devices from php.81 to 83 (that the one online).
Note that 1.0.8 has been released to correctly load the css file that style the popup, since changes applied on 1.0.7 (style files for all templates and not for prosilver only).
You can test it under 8.3 also here:
https://www.axew3.com/w3/forums/viewtopic.php?t=1639

**Comment by mrix2000** [comment]
Hello yes, no errors show, I basically rotate the image then click save then post and the image does not rotate. I have my own server so I can flip between php8.0 and php8.1 and when I flip it to php8.0 there is no issue and when I flip it to php8.1 it no longer works. I have tried your New 1.0.8 version but still the same unfortunately.
________________________________

**Comment by axew3** [comment]
I just switched my server to 8.1 
https://www.axew3.com/www/testphp/
so you can see/test that it is working fine here
https://www.axew3.com/w3/forum/
And there should be no reason why it should not, if not due to some misconfiguration on your server?
As tested by several more and by me, it is working fine into any Php 7.4> until latest 8.3.
I would like to see what it return for you, the file
_/ext/w3all/imageattachrotation/core/**fileRotate.php**_
so to exactly know what it is wrong for you.
But at moment, i should set this issue as resolved because it is working as you can see.
